INSERT INTO GUEST (MAIL, PASSWORD, TEMP) VALUES('mail1','pass1','peric');
INSERT INTO GUEST (MAIL, PASSWORD, TEMP) VALUES('mail2','pass2','peric2');
INSERT INTO GUEST (MAIL, PASSWORD, TEMP) VALUES('mail3','pass3','peric3');
INSERT INTO GUEST (MAIL, PASSWORD, TEMP) VALUES('mail4','pass4','peric4');


